/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings,dangling_library_doc_comments


class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
}

class _ImageResources {
  const _ImageResources();

  /// ![](D:\1LEARNING\CNTT\HK7\AdvancedMobile\Flutter_APP\your_ai\assets/images/google_logo.png)
  final google_logo = r'assets/images/google_logo.png';
}

class _SvgResources {
  const _SvgResources();
}
