name: Auto Deploy Flutter Web

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Random check for deployment (30% chance)
        id: random-check
        run: |
          RANDOM_NUMBER=$((RANDOM % 100))
          echo "Generated random number: $RANDOM_NUMBER"
          if [ $RANDOM_NUMBER -lt 30 ]; then
            echo "Deploying today (random number <$30)."
            echo "deploy=true" >> $GITHUB_ENV
          else
            echo "No deployment today (random number >=30)."
            echo "deploy=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        if: env.deploy == 'true'
        run: flutter pub get

      - name: Create .env file
        if: env.deploy == 'true'
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          echo "API_URL_KB=${{ secrets.API_URL_KB }}" >> .env
          echo "GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" >> .env

      - name: Build Flutter Web
        if: env.deploy == 'true'
        run: flutter build web --web-renderer canvaskit --base-href="/your_ai/"

      - name: Deploy to GitHub Pages
        if: env.deploy == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
